const NAVIGATE_TO_WELCOME_TAB = 0;
const NAVIGATE_TO_AUTH_TAB = 1;
const NAVIGATE_TO_NICKNAME_TAB = 2;
const NAVIGATE_TO_ALL_SET_TAB = 3;
const NAVIGATE_TO_HOME = 4;

const NAVIGATE_TO_AUTH_PHONE_TAB = 0;
const NAVIGATE_TO_AUTH_OTP_TAB = 1;